name: vet_reports_app
description: Veterinary Clinic Reports Application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  mongo_dart: ^0.10.4
  pdf: ^3.10.2
  printing: ^5.11.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  lottie: ^2.7.0
  share_plus: ^7.0.1
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.2.0
  intl_phone_number_input: ^0.7.3
  flutter_datetime_picker: ^1.5.1
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.5.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  flutter_phoenix: ^1.1.0
  flutter_svg: ^2.0.7
  realm: ^1.4.0
  pdfx: ^2.8.0
  uri: ^1.0.0
  syncfusion_flutter_datepicker: ^21.1.40 # Correct latest version (as of Oct 2023)
  device_info_plus: ^10.1.2
  libphonenumber_plugin: ^0.3.3
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.20.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
    - lib/l10n/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700