name: Flutter CI

on:
  workflow_dispatch: # Manual trigger only (remove if you want auto-trigger)

env:
  FLUTTER_VERSION: "3.19.5"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Updated from v3 to v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
